apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "go-templates.fullname" . }}
  labels:
    {{- include "go-templates.labels" . | nindent 4 }}
    comEspaco: " {{ 100 -}} > {{ 87 }}"
    semEspaco: " {{- 100 }} > {{- 87 -}}"
    {{ range $valor := .Values.Valores }}
    lab: "{{ $valor }}"
    {{end}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "go-templates.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "go-templates.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "go-templates.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{ range $index, $secret := .Values.secrets }}
            - name: OI
              valueFrom:
                secretKeyRef:
                  name: {{$secret}}
                  key: {{$index}}
            {{end}}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
